services:
  - type: web
    name: keepmoney-api
    env: docker
    plan: free
    region: singapore
    buildCommand: docker build -t keepmoney-api .
    startCommand: docker run -p $PORT:8080 keepmoney-api
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_HTTP_PORTS
        value: 8080